-- ═══════════════════════════════════════════════════════════════════════════
-- ConexionXD_v3.sql — Bitácora de cambios de esquema para desarrollo
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Vigencia: a partir del 2026-08-05.
--
-- Convención: toda sentencia ALTER TABLE, CREATE TABLE (o cualquier otro DDL)
-- que se implemente durante el desarrollo a partir de esta fecha debe
-- agregarse a este archivo, en el orden en que se va aplicando en el entorno
-- de desarrollo. La idea es mantener acá un registro único y cronológico de
-- todos los cambios de esquema, en vez de dispersarlos en scripts sueltos.
--
-- Este archivo NO se ejecuta directamente sobre producción. Es un borrador
-- de trabajo: más adelante, a partir de lo que quede acumulado acá, se
-- armará un script definitivo para aplicar en el ambiente de producción.
-- Producción ya está en funcionamiento, así que ningún cambio de esquema se
-- aplica ahí directamente — primero se documenta y valida en este archivo.
--
-- ═══════════════════════════════════════════════════════════════════════════
